const customError = require('../src/exceptions/customError')
const codeErrors = require('../src/exceptions/codeErrors')
const serviceLocator = require('../src/serviceLocator')()
const passwordIsValid = require('../src/services/users/passwordIsValid')
const favoriteCurrencyIsValid = require('../src/services/users/favoriteCurrencyIsValid')
const favoriteCurrencies = require('../src/utils/enums/favoriteCurrencies')
const manageToken = require('../src/utils/manageToken')
const handleCryptText = require('../src/utils/handleCryptText')
const userFilterMock = require('./mocks/userFilter')
const handleErrorsServices = require('../src/utils/handlerErrorsServices')
const requestHttp = require('../src/utils/requestHttp')
const keys = require('../src/config/keys')
const getUserService = require('../src/services/users/getUser')
const userCryptoCurrenciesFilter = require('./mocks/userCrytocurrenciesFilter')
const getUserCryptocurrencies = require('../src/services/users/getUserCryptoCurrencies')
const getAllCryptoCurrencies = require('../src/services/cryptoCurrencies/getAllCryptoCurrencies')
const favoriteCurrenciesEnum = require('../src/utils/enums/favoriteCurrencies')
serviceLocator.register('exceptions.customError', customError)
serviceLocator.register('exceptions.codeErrors', codeErrors)
serviceLocator.register('services.passwordIsValid', passwordIsValid)
serviceLocator.register('services.favoriteCurrencyIsValid', favoriteCurrencyIsValid)
serviceLocator.register('utils.handleCryptText', handleCryptText)
serviceLocator.register('utils.favoriteCurrencies', favoriteCurrencies)
serviceLocator.register('filters.user', userFilterMock)
serviceLocator.register('repositories.user', { createUser: jest.fn(), addCryptoCurrency: jest.fn() })
serviceLocator.register('utils.manageToken', manageToken)
serviceLocator.register('utils.handleErrorsServices', handleErrorsServices)
serviceLocator.register('utils.requestHttp', requestHttp)
serviceLocator.register('config.keys', keys)
serviceLocator.register('services.getUser', getUserService)
serviceLocator.register('filters.userCryptocurrencies', userCryptoCurrenciesFilter)
serviceLocator.register('services.getUserCryptocurrencies', getUserCryptocurrencies)
serviceLocator.register('services.getAllCryptoCurrencies', getAllCryptoCurrencies)
serviceLocator.register('utils.favoriteCurrenciesEnum', favoriteCurrenciesEnum)

module.exports = serviceLocator
